"""ReportCurator Node — 报告生成"""
from __future__ import annotations
import sys, json, time
from pathlib import Path
from datetime import datetime
from typing import Optional, Dict, Any

PROJECT_ROOT = Path(__file__).parent.parent.parent
sys.path.insert(0, str(PROJECT_ROOT))

from workflow.state import BioAnalysisState
from workflow.registry import StateRegistry

SCRIPT_DIR = PROJECT_ROOT / "scripts"


def _generate_simple_report(state: BioAnalysisState, hyp_dir: Path) -> Optional[str]:
    """
    生成简洁友好的 Markdown 报告。
    用于无完整数据（LiteratureMiner-5 未找到有效数据集）时。
    """
    hyp_id = state["hypothesis_id"]
    hyp_text = state.get("hypothesis_text", "?")
    p1_type = state.get("hypothesis_parser_type", "?")
    p1_e1 = state.get("hypothesis_parser_entity1", "?")
    p1_e2 = state.get("hypothesis_parser_entity2", "—")
    p2_n_papers = state.get("literature_miner_n_papers", 0)
    p2_n_datasets = state.get("literature_miner_n_datasets", 0)
    p3_n_downloaded = state.get("geo_retriever_n_downloaded", 0)
    p4_n_analyzed = state.get("effect_size_analyst_n_analyzed", 0)
    p5_score = state.get("meta_analyst_reliability_score", 0)
    p5_grade = state.get("meta_analyst_grade", "⚪ N/A")

    md = f"""# 🧬 Biological Hypothesis Validation Report

## 基本信息

| 项目 | 内容 |
|------|------|
| **Hypothesis ID** | `{hyp_id}` |
| **Generated** | {datetime.now().strftime('%Y-%m-%d %H:%M')} |
| **Hypothesis** | {hyp_text} |
| **Analysis Type** | {p1_type} |
| **Entity 1** | {p1_e1} |
| **Entity 2** | {p1_e2} |

---

## ⚠️ 验证未完成（数据不足）

本假设未能完成完整的假设验证流程，主要原因是 **GEO 数据库中未找到足够的匹配数据集**。

### 执行摘要

| 阶段 | 状态 | 结果 |
|------|------|------|
| HypothesisParser — 假设解析 | ✅ 完成 | {p1_type} · {p1_e1} |
| LiteratureMiner — 文献挖掘 | ✅ 完成 | {p2_n_papers} 篇文献，{p2_n_datasets} 个推荐数据集 |
| GEORetriever — GEO 数据下载 | ✅ 完成 | {p3_n_downloaded} 个数据集 |
| EffectSizeAnalyst — 效应量分析 | ⚠️ 跳过 | 无可用数据集 |
| MetaAnalyst — 元分析 | ⚠️ 跳过 | 无可用数据 |
| ReportCurator — 报告生成 | ✅ 完成 | 本报告 |

### 可能原因

1. **文献未找到相关 scRNA-seq 数据集**：假设中的细胞类型/癌症组合在 GEO 中缺乏公开单细胞数据
2. **关键词匹配不足**：建议在假设中加入更具体的基因或标记物名称
3. **数据类型不匹配**：当前仅搜索 scRNA-seq 数据，未包含 bulk RNA-seq

### 改进建议

- 尝试更具体的基因集（如具体的 marker 基因名）
- 使用已验证过的假设类型，如：
  - *"T cell exhaustion in tumor microenvironment"*
  - *"SPP1+ macrophage predicts poor survival in HCC"*
- 或使用 `resume` 命令从 LiteratureMiner 重新运行，调整搜索关键词

---

*Generated by Bio-Analysis System · {datetime.now().strftime('%Y-%m-%d %H:%M')}*
"""

    reports_dir = hyp_dir / "reports"
    reports_dir.mkdir(exist_ok=True)
    report_path = reports_dir / "final_report.md"
    report_path.write_text(md, encoding="utf-8")
    return str(report_path)


def report_curator(state: BioAnalysisState) -> BioAnalysisState:
    """
    ReportCurator: 生成最终报告。

    优先调用 report_curator_report_generator.py。
    若无完整数据（meta_analyst_status == "no_data"）或脚本失败，
    则生成简洁友好报告。
    """
    hyp_id = state["hypothesis_id"]
    registry = StateRegistry(hyp_id)

    new_state = dict(state)
    new_state["report_curator_status"] = "running"
    registry.set(new_state, phase=None)

    p5_status = state.get("meta_analyst_status", "")

    try:
        script = SCRIPT_DIR / "report_curator_report_generator.py"
        report_path = None

        # 尝试调用完整报告生成器
        if script.exists() and p5_status != "no_data":
            import subprocess
            result = subprocess.run(
                [sys.executable, str(script), "--hypothesis-dir", str(registry.hyp_dir)],
                capture_output=True, text=True, timeout=60,
            )
            if result.returncode == 0:
                # 成功，找报告文件
                report_paths = list(registry.hyp_dir.glob("reports/*final_report.md"))
                report_path = str(report_paths[0]) if report_paths else None

        # 如果上面没有生成报告（无数据 或 脚本失败），生成简洁版
        if not report_path:
            print(f"[ReportCurator] 📝 生成简洁报告（数据不足模式）...")
            report_path = _generate_simple_report(new_state, registry.hyp_dir)

        new_state.update({
            "report_curator_report_path": report_path,
            "report_curator_status": "done",
            "report_curator_error": None,
            "current_phase": "final",
        })
        if "report_curator" not in new_state["checkpoints"]:
            new_state["checkpoints"] = new_state["checkpoints"] + ["report_curator"]
        registry.set(new_state, phase="report_curator")
        print(f"[ReportCurator] ✅ Report: {report_path}")

    except Exception as e:
        # 最后兜底：确保至少有个报告
        try:
            report_path = _generate_simple_report(new_state, registry.hyp_dir)
            new_state.update({
                "report_curator_report_path": report_path,
                "report_curator_status": "done",
                "report_curator_error": f"（简化报告）{e}",
                "current_phase": "final",
            })
            registry.set(new_state, phase="report_curator")
            print(f"[ReportCurator] ✅ 简化报告: {report_path}")
        except Exception:
            new_state.update({
                "report_curator_status": "failed",
                "report_curator_error": str(e),
            })
            new_state.setdefault("errors", []).append(f"Phase6: {e}")
            registry.set(new_state, phase=None)
            print(f"[ReportCurator] ❌ Failed: {e}")

    return new_state


# ─────────────────────────────────────────────
# 边（Conditional Edges）
# ─────────────────────────────────────────────

def should_final(state: BioAnalysisState) -> str:
    """ReportCurator → report_curator_done 终态"""
    return "final"
